# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [5]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]

height2 = np.array(height)
weight2 = np.array(weight)
print(weight2,height2)

BMI = (weight2 / (height2**2)) *730
print(BMI)

[110 120 130 140 150 160 170] [69 70 71 72 73 74 75]
[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [46]:
"""
Example Result
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
# def makeMatrix(low,high,shape,data_type = float): -- Example
#     pass

def makeMatrix(low, high):
    p = np.random.rand(low,high)
    new_P=p.reshape(6,4) # these bounds must multiply to equal same as product of low*high
    print(p)
    print(new_P)

makeMatrix(2,12)

[[0.57900693 0.45816905 0.92662586 0.92828602 0.05609005 0.74031184
  0.80314834 0.59932671 0.68021131 0.00155309 0.33554198 0.72594068]
 [0.79533897 0.97476488 0.16487463 0.81929059 0.59860441 0.29018725
  0.66970499 0.12412798 0.9266619  0.44650035 0.18225473 0.43709279]]
[[0.57900693 0.45816905 0.92662586 0.92828602]
 [0.05609005 0.74031184 0.80314834 0.59932671]
 [0.68021131 0.00155309 0.33554198 0.72594068]
 [0.79533897 0.97476488 0.16487463 0.81929059]
 [0.59860441 0.29018725 0.66970499 0.12412798]
 [0.9266619  0.44650035 0.18225473 0.43709279]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [ ]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_csv(filename, delim =','): #most csvs are comma separated 
    #define an empty list to store data
    data_a=[]
    with open(filename, encoding='utf-8') as openedFile: #open another file in background using without manually closing background file
        # use csv package reader method to read that file
        readData = csv.reader(openedFile, delimiter=delim)
        # loop over info and append data row by row to list data_a
        for row in readData:
            data_a.append(row)
        return data_a
    
csv_data2018=open_csv('./files/redsox_2018_hitting.txt')
print(csv_data2018)
csv_data2017=open_csv('./files/redsox_2017_hitting.txt')
print(csv_data2017)

In [59]:
"""
Example Result - Not the actual result
Boston 18 had more SLG in 2018
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
"""

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, delim=','):
    return np.genfromtxt(filename, delimiter=delim, skip_header=1, usecols=np.arange(0,24), invalid_raise=False, names=FIELDS, dtype=DATATYPES)
    #genfromtxt - generate from text file, generate an empty array from a text file, can organize with parameters
    # skip_header - tells how many header rows we have, in this case the first row only based on text file
    # use_cols = how many columns are there - 24 so create range from 0, 24
    # invalid_raise = don't throw an error if something is invalid
    # names of our columns will be FIELDS list from above
    # datatypes list will be datatypes list from above

bs2017 = load_data('./files/redsox_2017_hitting.txt')
slg2017 = bs2017['SLG']
print(slg2017)
bs2018 = load_data('./files/redsox_2018_hitting.txt')
slg2018 = bs2018['SLG']
print(slg2018)

def compare_slg(set1, set2):
    if len(set1)>len(set2):
        print('2017 had a better SLG')
    elif len(set2)>len(set1):
        print('2018 had a beter SLG')
    elif len(set2)==len(set1):
        print('both years had the same SLG')
compare_slg(slg2017,slg2018)

[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]
[0.279 0.433 0.388 0.522 0.433 0.465 0.403 0.64  0.629 0.411 0.283 0.328
 0.395 0.507 0.311 0.415 0.389 0.261 0.091 0.167]
2017 had a better SLG
